### ISSUE TITLE
[OG Image] How to fetch fonts throw proxy?

### ISSUE THREAD

**Issue by kingyue737** [harlan-zw/nuxt-seo#156]
### Details

When I `nuxi build`, the following error occurs:
```
 ERROR  [nuxt] [request error] [unhandled] [500] fetch failed                                                                                                                                    21:44:05  
  at Object.fetch (node:internal/deps/undici/undici:11730:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async sendProxy (/C:/Repositories/nustarnuclear.com/node_modules/.pnpm/h3@1.10.0/node_modules/h3/dist/index.mjs:1080:20)
  at async Object.handler (/C:/Repositories/nustarnuclear.com/node_modules/.pnpm/h3@1.10.0/node_modules/h3/dist/index.mjs:1676:19)
  at async toNodeHandle (/C:/Repositories/nustarnuclear.com/node_modules/.pnpm/h3@1.10.0/node_modules/h3/dist/index.mjs:1886:7)
  at async ufetch (/C:/Repositories/nustarnuclear.com/node_modules/.pnpm/unenv@1.9.0/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async generateRoute (/C:/Repositories/nustarnuclear.com/node_modules/.pnpm/nitropack@2.8.1/node_modules/nitropack/dist/shared/nitro.0a84349b.mjs:113:17)
  at async Promise.all (index 2)
  at async runParallel (/C:/Repositories/nustarnuclear.com/node_modules/.pnpm/nitropack@2.8.1/node_modules/nitropack/dist/shared/nitro.0a84349b.mjs:245:3)
  at async prerender (/C:/Repositories/nustarnuclear.com/node_modules/.pnpm/nitropack@2.8.1/node_modules/nitropack/dist/shared/nitro.0a84349b.mjs:199:3)

  ├─ /__og-image__/font/Noto+Sans+SC/400.ttf (10333ms)                                                                                                                                     nitro 21:44:06
  │ └── Error: [500]
```
Maybe because I'm in China?
Even with `$http:proxy`/`$https:proxy` set in terminal, the build still failed.

**Comment by harlan-zw** [comment]
> Maybe because I'm in China?

Seems likely, you may need to download the font locally and load it in from the public directory.

How would you typically get around these constaints?

**Comment by kingyue737** [comment]
Just found out I opened this issue in the wrong repo. I should have opened it in [nuxt-modules/og-image](https://github.com/nuxt-modules/og-image)

If the proxy doesn't work, I will use a mirror server deployed in China.

Currently, by manually patching the following line with mirror URL, I can build successfully 🎉
https://github.com/nuxt-modules/og-image/blob/0695288b197f929279639f74dca85808c01592fd/src/runtime/server/routes/__og-image__/font-%5Bname%5D-%5Bweight%5D.%5Bextension%5D.ts#L47
Is it convenient to add an option to modify the URL? Or I can put font files in `/public` and `.gitignore`🤔

**Comment by harlan-zw** [comment]
No problem with the repo. Is the mirror URL public and stable? Happy to add in a config to use that, otherwise can just have a full domain override

**Comment by kingyue737** [comment]
There are several public mirrors. Previously, I used a mirror from a famous university but now is unavailable.

Yesterday I tried https://fonts.font.im which seems to be available since 2016.
https://fonts.loli.net is another mirror that works currently.

It's hard to say if they will be stable forever. Furthermore, the download speed is a little slow and fonts file needs to be fetched each time I build the project (Wonder if font files can be cached):
```
ℹ Prerendering 4 routes                                                                                                                                                 nitro 11:53:29
  ├─ /__studio.json (25ms)                                                                                                                                               nitro 11:53:29
  ├─ /api/_content/cache.1704599537249.json (1452ms)                                                                                                                     nitro 11:53:30
  ├─ /__og-image__/font/Noto+Sans+SC/400.ttf (15505ms)                                                                                                                   nitro 11:53:45
  ├─ /__og-image__/font/Noto+Sans+SC/700.ttf (22620ms) 
```

Currently, I think loading the font locally as you recommend may be the better choice

**Comment by harlan-zw** [comment]
Thanks for your help on this, I've introduced a [googleFontMirror](https://nuxtseo.com/og-image/guides/custom-fonts#google-font-api-mirror) config that can be used in the latest version of Nuxt OG Image.

Will be in the next Nuxt SEO RC.
