### ISSUE TITLE
2.0.0-rc6: $fetch is not defined

### ISSUE THREAD

**Issue by sameignatovich** [harlan-zw/nuxt-seo#178]
### Describe the bug

Hello!

I just installed module and my nuxt wont start. I receive next error after start:

```
 ERROR  Cannot restart nuxt:  $fetch is not defined                                                         11:14:49 AM

  at setup (node_modules/.pnpm/@nuxtjs+seo@2.0.0-rc.6_@lezer+common@1.2.1_@nuxt+devtools@1.0.8_@unhead+shared@1.8.10_@vue+co_oydvfc273zzjhkajuwxvhgxkgi/node_modules/@nuxtjs/seo/dist/module.mjs:88:7)
  at async normalizedModule (node_modules/.pnpm/@nuxt+kit@3.10.0_rollup@4.9.6/node_modules/@nuxt/kit/dist/index.mjs:2112:17)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.9.3_rollup@4.9.6/node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (node_modules/.pnpm/nuxt@3.9.3_eslint@8.56.0_rollup@4.9.6_sass@1.70.0_typescript@5.3.3_vite@5.0.12/node_modules/nuxt/dist/index.mjs:3858:7)
  at async NuxtDevServer._load (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/dev2.mjs:253:5)
  at async NuxtDevServer.load (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/dev2.mjs:185:7)
  at async _applyPromised (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/dev2.mjs:105:10)
```

my config:
```typescript
export default defineNuxtConfig({
  css: ['@/assets/styles/main.scss'],
  devtools: { enabled: true },
  i18n: {
    compilation: {
      strictMessage: false,
    },
    customRoutes: 'config',
    defaultLocale: 'kz',
    detectBrowserLanguage: {
      cookieKey: 'i18n_redirected',
      redirectOn: 'root',
      useCookie: true,
    },
    langDir: 'locales',
    lazy: true,
    locales: [...],
    pages: {...},
    strategy: 'prefix_except_default',
  },
  modules: ['@nuxtjs/i18n', '@nuxtjs/seo'],
  runtimeConfig: {
    public: {
      baseApiUrl: '',
      i18n: {
        baseUrl: '',
      },
      siteUrl: '',
    },
  },
  site: {
    trailingSlash: true,
  },
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@import "~/assets/styles/global.scss";',
        },
      },
    },
  },
  ogImage: {
    enabled: false
  },
  sitemap: {
    enabled: false
  },
  robots: {
    enabled: false
  },
  seoExperiments: {
    enabled: false
  },
  schemaOrg: {
    enabled: false
  },
  linkChecker: {
    enabled: false
  }
});
```

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.9.3`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `pnpm@8.14.1`
- Builder:          `-`
- User Config:      `css`, `devtools`, `i18n`, `modules`, `runtimeConfig`, `site`, `vite`, `ogImage`, `sitemap`, `robots`, `seoExperiments`, `schemaOrg`, `linkChecker`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0`, `@nuxtjs/seo@2.0.0-rc.6`
- Build Modules:    `-`
```

**Comment by sameignatovich** [comment]
I added import to module.mjs and error was gone. Can you add strict import of $fetch in project?

**Comment by harlan-zw** [comment]
Thanks guys, interesting bug. Seems like `$fetch` worked fine without an import until I added a timeout option to it :sweat_smile: 

I pushed up RC 7 with a fix (explicit import)
