### ISSUE TITLE
Unable to use with Docker

### ISSUE THREAD

**Issue by creazy231** [harlan-zw/nuxt-seo#226]
### Describe the bug

Running `yarn install` gives me the following error:

```
#11 0.432 yarn install v1.22.22
#11 0.534 [1/5] Validating package.json...
#11 0.540 [2/5] Resolving packages...
#11 1.288 [3/5] Fetching packages...
#11 1.570 error Error: https://npm.fontawesome.com/@fortawesome/free-regular-svg-icons/-/6.5.2/free-regular-svg-icons-6.5.2.tgz: Request failed "401 Unauthorized"
#11 1.570 at ResponseError.ExtendableBuiltin (/nix/store/hn80x7lgvfxs8zvzlvk3wmhq7qdifv4p-yarn/lib/cli.js:696:66)
#11 1.570 at new ResponseError (/nix/store/hn80x7lgvfxs8zvzlvk3wmhq7qdifv4p-yarn/lib/cli.js:802:124)
#11 1.570 at Request. (/nix/store/hn80x7lgvfxs8zvzlvk3wmhq7qdifv4p-yarn/lib/cli.js:66750:16)
#11 1.570 at Request.emit (node:events:517:28)
#11 1.570 at module.exports.Request.onRequestResponse (/nix/store/hn80x7lgvfxs8zvzlvk3wmhq7qdifv4p-yarn/lib/cli.js:142287:10)
#11 1.570 at ClientRequest.emit (node:events:517:28)
#11 1.570 at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
#11 1.570 at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
#11 1.570 at TLSSocket.socketOnData (node:_http_client:541:22)
#11 1.570 at TLSSocket.emit (node:events:517:28)
```

Source:
```
=> Found "@fortawesome/free-regular-svg-icons@6.5.2"
info Reasons this module exists
   - "_project_#web#@nuxtjs#seo#nuxt-og-image#vanilla-jsoneditor" depends on it
   - Hoisted from "_project_#web#@nuxtjs#seo#nuxt-og-image#vanilla-jsoneditor#@fortawesome#free-regular-svg-icons"
   ```

**Comment by harlan-zw** [comment]
I think you may have a NPM relation set up to point `@fortawesome` to npm.fontawesome.com, the package should point to https://www.npmjs.com/package/@fortawesome/free-regular-svg-icons.
