### ISSUE TITLE
Nuxt Devtools failing to start

### ISSUE THREAD

**Issue by MichaelPrecel** [harlan-zw/nuxt-seo#242]
### Describe the bug

Module is preventing Nuxt dev from working with devtools enabled. Issue is avoided if `@nuxtjs/seo` is removed from modules in the config. `Node v20.11.1`.

```
"@nuxtjs/seo": "2.0.0-rc.10",
"nuxt": "^3.11.2",
```

```
 ERROR  Cannot start nuxt:  Failed to get devtools context.                                                       3:49:58 PM

  at extendServerRpc (node_modules/.pnpm/@nuxt+devtools-kit@1.3.2_nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+no_ssmgxyrjhpvgwuhnbn2n6k6p4i/node_modules/@nuxt/devtools-kit/dist/index.mjs:96:11)
  at node_modules/.pnpm/nuxt-simple-robots@4.0.0-rc.16_@nuxt+devtools@1.3.2_@unocss+reset@0.60.3_floating-vue@5.2.2_@_ghuptqxvlvje7s7d7us3y7ynmq/node_modules/nuxt-simple-robots/dist/module.mjs:318:5
  at node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs:48:66
  at node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs:48:56
  at async enableModule (/Users/michaelprecel/.nvm/versions/node/v16.18.0/lib/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:8466:3)
  at async normalizedModule (/Users/michaelprecel/.nvm/versions/node/v16.18.0/lib/node_modules/@nuxt/devtools/node_modules/@nuxt/kit/dist/index.mjs:170:17)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.11.2_rollup@4.18.0/node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_xpwvl5rbsrfcbbgn2t455xwlbi/node_modules/nuxt/dist/index.mjs:4233:7)
  at async NuxtDevServer._load (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/dev2.mjs:6879:5)
  at async NuxtDevServer.load (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/dev2.mjs:6811:7)                                                                                                                  

### Reproduction

_No response_

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.0.6
- Builder:          -
- User Config:      devtools, app, vite, modules, css, postcss, i18n, build, experimental, imports, pinia, image, sanity, site
- Runtime Modules:  @nuxtjs/sanity@1.11.3, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.10.0, @nuxt/image@1.7.0, @vueuse/motion/nuxt@2.1.0, @nuxtjs/i18n@8.3.1, nuxt-time@0.1.3
- Build Modules:    -
```

**Comment by remihuigen** [comment]
Same here!

```
"@nuxtjs/seo": "2.0.0-rc.10",
"nuxt": "^3.12.2"
```

**Comment by harlan-zw** [comment]
This appears to be an upstream issue with devtools, can you confirm if it's still an issue with the latest versions?

**Comment by remihuigen** [comment]
I can confirm the issue is still there with 

```
"@nuxtjs/seo": "2.0.0-rc.15",
"nuxt": "^3.12.3"
```
