### ISSUE TITLE
Cannot stringify a function

### ISSUE THREAD

**Issue by adamdehaven** [harlan-zw/nuxt-seo#278]
### Describe the bug

I'm not sure how to explain to reproduce (sorry in advance, I know that's not helpful) but utilizing `@nuxtjs/seo@2.0.0-rc.16` I now get the following error:

```
[nuxt] [request error] [unhandled] [500] Cannot stringify a function
  at flatten (/Users/adam/Dev/portal/node_modules/.pnpm/devalue@5.0.0/node_modules/devalue/src/stringify.js:44:10)
  at flatten (/Users/adam/Dev/portal/node_modules/.pnpm/devalue@5.0.0/node_modules/devalue/src/stringify.js:169:43)
  at flatten (/Users/adam/Dev/portal/node_modules/.pnpm/devalue@5.0.0/node_modules/devalue/src/stringify.js:169:43)
  at Module.stringify (/Users/adam/Dev/portal/node_modules/.pnpm/devalue@5.0.0/node_modules/devalue/src/stringify.js:181:16)
  at innerHTML (/Users/adam/Dev/portal/node_modules/.pnpm/nuxt-og-image@3.0.0-rc.64_magicast@0.3.4_rollup@4.18.0_vite@5.3.3_@types+node@20.14.11_less@3_zno4y7vcemg5pv7ga4dbbnrtne/node_modules/nuxt-og-image/dist/runtime/nuxt/utils.js:57:38)
  at resolveUnref (/Users/adam/Dev/portal/node_modules/.pnpm/@unhead+vue@1.9.15_vue@3.4.31_typescript@5.5.3_/node_modules/@unhead/vue/dist/shared/vue.cf295fb1.mjs:8:36)
  at resolveUnrefHeadInput (/Users/adam/Dev/portal/node_modules/.pnpm/@unhead+vue@1.9.15_vue@3.4.31_typescript@5.5.3_/node_modules/@unhead/vue/dist/shared/vue.cf295fb1.mjs:13:16)
  at <anonymous> (/Users/adam/Dev/portal/node_modules/.pnpm/@unhead+vue@1.9.15_vue@3.4.31_typescript@5.5.3_/node_modules/@unhead/vue/dist/shared/vue.cf295fb1.mjs:23:20)
  at Array.map (<anonymous>)
  at resolveUnrefHeadInput (/Users/adam/Dev/portal/node_modules/.pnpm/@unhead+vue@1.9.15_vue@3.4.31_typescript@5.5.3_/node_modules/@unhead/vue/dist/shared/vue.cf295fb1.mjs:20:28)
```

![cannot stringify a function](https://github.com/user-attachments/assets/7b1fcbde-a481-4b80-8043-3e290168b599)

The error is thrown when loading a page via SSR in development mode. If I then navigate client-side to another page, I can continue, but it's throwing a 500 error on any reload of an SSR page.

I have OgImage enabled, and call the `defineOgImageComponent` and `useSeoMeta` functions in my template:

```ts
useSeoMeta({
  title: () => pageData.value?.title || ast.value?.data?.title || '',
  description: () => ast.value?.data?.description,
})

defineOgImageComponent('NuxtSeo', {
  title: pageData.value?.title || ast.value?.data?.title || '',
  description: ast.value?.data?.description,
})
```

**Comment by adamdehaven** [comment]
@harlan-zw it looks like the breaking change was introduced in the `v2.0.0-rc.12` release: https://github.com/harlan-zw/nuxt-seo/compare/v2.0.0-rc.11...v2.0.0-rc.12

**Comment by adamdehaven** [comment]
Apologies, ignore this. Downstream configuration issue; sorry for the noise

**Comment by harlan-zw** [comment]
All good :) I'm guessing you tried to do something like this:

```ts
defineOgImageComponent('NuxtSeo', {
  title: () => pageData.value?.title || ast.value?.data?.title || '',
})
```

I may add support for this as the reactivity isn't immediately resolved anyway and can just re-use the same logic from `useSeoMeta`

**Comment by adamdehaven** [comment]
> I'm guessing you tried to do the equivalent of this

Exactly this, yes 😅 

> I may add support for this as the reactivity isn't immediately resolved anyway and can just re-use the same logic from `useSeoMeta`

Yes IMO that would be ideal so that providing the values works the same between the separate functions. 
 
> FWIW you don't need to provide a `title` and `description` in `defineOgImageComponent` if they're the same as useSeoMeta data, they will be inferred already

Ah! I didn’t know this; awesome. Is this in the docs anywhere? (If not, can I suggest adding a note before the major version release?)
