### ISSUE TITLE
Build failing - revsg-wasm dependency not found

### ISSUE THREAD

**Issue by AdamBD** [harlan-zw/nuxt-seo#293]
### Describe the bug

```
[nitro]  ERROR  Error: Could not load /tmp/build_91253e2d/node_modules/@resvg/resvg-wasm/index_bg.wasm?module (imported by node_modules/nuxt-og-image/dist/runtime/nitro/og-image/bindings/resvg/wasm.mjs): ENOENT: no such file or directory, open '/tmp/build_91253e2d/node_modules/@resvg/resvg-wasm/index_bg.wasm?module'
undefined
 ERROR  Could not load /tmp/build_91253e2d/node_modules/@resvg/resvg-wasm/index_bg.wasm?module (imported by node_modules/nuxt-og-image/dist/runtime/nitro/og-image/bindings/resvg/wasm.mjs): ENOENT: no such file or directory, open '/tmp/build_91253e2d/node_modules/@resvg/resvg-wasm/index_bg.wasm?module'
  at async open (node:internal/fs/promises:639:25)
  at async readFile (node:internal/fs/promises:1249:14)
  at async node_modules/rollup/dist/es/shared/node-entry.js:18670:24
  at async Queue.work (node_modules/rollup/dist/es/shared/node-entry.js:19705:32) 
 ERROR  Could not load /tmp/build_91253e2d/node_modules/@resvg/resvg-wasm/index_bg.wasm?module (imported by node_modules/nuxt-og-image/dist/runtime/nitro/og-image/bindings/resvg/wasm.mjs): ENOENT: no such file or directory, open '/tmp/build_91253e2d/node_modules/@resvg/resvg-wasm/index_bg.wasm?module'
```

### System / Nuxt Info

```Shell
{
	"devDependencies": {
		"@nuxtjs/seo": "^2.0.0-rc.10",
		"nuxt": "^3.5.0",
		"nuxt-hydration": "^0.5.3",
		"nuxt-icon": "^0.6.10",
	},
}
```

**Comment by harlan-zw** [comment]
Hi, I will need reproduction details.

Also please use the latest version of Nuxt SEO and Nuxt

**Comment by AdamBD** [comment]
upgrading to `"@nuxtjs/seo": "^2.0.0-rc.18",` solved this for me
