### ISSUE TITLE
Combining @nuxtjs/robots with @nuxtjs/sitemap causes pre-generation to fail on sitemap

### ISSUE THREAD

**Issue by NikhilVerma** [harlan-zw/nuxt-seo#302]
## Steps to reproduce

- Use Nuxt 3 with config defined below
- Try to visit /sitemap.xml

You get this error

```
500
Cannot read properties of undefined (reading 'req')

at getRequestHeader (/xxx/node_modules/h3/dist/index.mjs:316:19)
at getPathRobotConfig (/xxx/node_modules/@nuxtjs/robots/dist/runtime/nitro/composables/getPathRobotConfig.js:19:43)
at  (/xxx/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/sitemap/urlset/filter.js:21:10)
at Array.filter ()
at filterSitemapUrls (/xxx/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/sitemap/urlset/filter.js:9:16)
at buildSitemap (/xxx/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/sitemap/builder/sitemap.js:80:24)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at createSitemap (/xxx/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/sitemap/nitro.js:25:17)
at async /xxx/node_modules/h3/dist/index.mjs:1980:19
```

This seems to happen because we are trying to get user agent from h3 but the event is not a valid request event, it's of the shape `{ loc: 'string', _key: 'string'}`  so it can't find the headers

## Steps to fix

For now I patched the dependency with this code

```patch
diff --git a/dist/runtime/nitro/composables/getPathRobotConfig.js b/dist/runtime/nitro/composables/getPathRobotConfig.js
index 38f02344ce9a122b72d02046a66d5dcffa5102b0..79f375aa33d3e49665814a0dec7f3e202ee18e70 100644
--- a/dist/runtime/nitro/composables/getPathRobotConfig.js
+++ b/dist/runtime/nitro/composables/getPathRobotConfig.js
@@ -16,7 +16,7 @@ export function getPathRobotConfig(e, options) {
     }
   }
   const path = options?.path || e.path;
-  const userAgent = options?.userAgent || getRequestHeader(e, "User-Agent");
+  const userAgent = options?.userAgent || (e.node ? getRequestHeader(e, "User-Agent") : 'na');
   const nitroApp = useNitroApp();
   const groups = [
     // run explicit user agent matching first
```

## Nuxt Config

```ts
export default defineNuxtConfig({
	modules: [
		"@nuxtjs/robots",
		"@nuxtjs/sitemap",
	],

	experimental: {
		inlineRouteRules: true
	},

	robots: process.env.APP_ENV?.includes("prod")
		? { allow: "/" }
		: { disallow: "/" },

	site: {
		name: "XXX",
		url: process.env.URL
	},

	nitro: {
		prerender: {
			crawlLinks: true,
			routes: ["/sitemap.xml"]
		}
	},

	compatibilityDate: "2024-07-31"
});
```

### System / Nuxt Info

```Shell
"nuxt": "^3.12.4"
"@nuxtjs/sitemap": "^5.3.5"
"@nuxtjs/robots": "^4.0.2"
```

**Comment by wokalek** [comment]
Same error.

**Comment by harlan-zw** [comment]
Hi, could you try the v6 beta for the sitemap module? It may fix this, it had a massive internal refactor. I'll try to ship it as stable either tomorrow or the day after.

**Comment by NikhilVerma** [comment]
@harlan-zw I tried on the beta but the same error persists. (Cleared Nuxt cache `.nuxt .output` etc).

```
 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'req')              23:11:37
  at getRequestHeaders (/xxx/h3/dist/index.mjs:303:32)
  at getRequestHeader (/xxx/h3/dist/index.mjs:311:19)
  at getPathRobotConfig (./.nuxt/prerender/chunks/runtime.mjs:1663:43)
  at ./.nuxt/prerender/chunks/runtime.mjs:2514:10
  at Array.filter (<anonymous>)
  at filterSitemapUrls (./.nuxt/prerender/chunks/runtime.mjs:2503:16)
  at buildSitemap (./.nuxt/prerender/chunks/runtime.mjs:2852:24)
  at async createSitemap (./.nuxt/prerender/chunks/runtime.mjs:2981:17)
  at async Object.handler (/xxx/h3/dist/index.mjs:1975:19)
  at async toNodeHandle (/xxx/h3/dist/index.mjs:2266:7)
```

**Comment by Saggre** [comment]
I'm also facing this issue

**Comment by renataleal335** [comment]
estou com o mesmo problema
