### ISSUE TITLE
Error when using useBreadcrumbItems – A composable that requires access to the Nuxt instance was called outside of a plugin

### ISSUE THREAD

**Issue by thorge** [harlan-zw/nuxt-seo#310]
### Describe the bug

I receive the following error when using `useBreadcrumbItems` as in #231:

```sh
 ERROR  [nuxt] [request error] [unhandled] [500] [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin,
 Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/aut
o-imports#vue-and-nuxt-composables.                                                                                                           
  at Module.useNuxtApp (./node_modules/nuxt/dist/app/nuxt.js:246:13)                                                                          
  at Module.useRoute (./node_modules/nuxt/dist/app/composables/router.js:24:32)                                                               
  at ComputedRefImpl.fn (./node_modules/@nuxtjs/seo/dist/runtime/nuxt/composables/useBreadcrumbItems.js:44:145)                               
  at refreshComputed (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:361:28)                                                           
  at get value [as value] (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:1639:5)                                                      
  at ComputedRefImpl.fn (./node_modules/@nuxtjs/seo/dist/runtime/nuxt/composables/useBreadcrumbItems.js:98:69)                                
  at refreshComputed (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:361:28)                                                           
  at get value [as value] (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:1639:5)                                                      
  at unref (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:1490:29)                                                                    
  at resolveUnref (./node_modules/@unhead/vue/dist/shared/vue.40986ab9.mjs:8:42)
```

It worked, before I upgraded some packages:

```sh
diff --git a/package.json b/package.json
index 4ef0e17..1047761 100644
--- a/package.json
+++ b/package.json
@@ -9,30 +9,30 @@
   },
   "dependencies": {
     "@nuxt/content": "^2.13.2",
-    "@nuxt/vite-builder": "^3.12.4",
+    "@nuxt/vite-builder": "^3.13.1",
-    "axios": "^1.7.4",
+    "axios": "^1.7.7",
-    "sass": "^1.77.8",
+    "sass": "^1.78.0",
   },
   "devDependencies": {
-    "@nuxtjs/i18n": "^8.5.0",
+    "@nuxtjs/i18n": "^8.5.1",
     "@nuxtjs/leaflet": "^1.2.2",
-    "@nuxtjs/seo": "^2.0.0-rc.19",
-    "@pinia/nuxt": "^0.5.3",
+    "@nuxtjs/seo": "^2.0.0-rc.20",
+    "@pinia/nuxt": "^0.5.4",
-    "nuxt": "^3.12.4",
+    "nuxt": "^3.13.1",
     "slugify": "^1.6.6",
     "vite-plugin-vuetify": "^2.0.4",
-    "vue": "^3.4.38",
+    "vue": "^3.5.1",
     "vue-router": "^4.4.3",
-    "vuetify": "^3.7.0"
+    "vuetify": "^3.7.1"
   }
 }
```

### Reproduction

https://codesandbox.io/p/devbox/breadcrumbitems-test-3jv34t?file=%2Fapp.vue

### System / Nuxt Info

```Shell
------------------------------                                                                                                                
- Operating System: Linux
- Node Version:     v21.6.1
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      ssr, hooks, alias, app, site, typescript, build, modules, content, i18n, vite, nitro, runtimeConfig, devServerHandlers, compatibilityDate
- Runtime Modules:  @pinia/nuxt@0.5.4, @nuxt/content@2.13.2, @nuxtjs/i18n@8.5.1, @nuxtjs/seo@2.0.0-rc.20
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Thanks for the reproduction, this appears to be fixed in RC 21.

**Comment by thorge** [comment]
I’ve just tested RC 21, and everything is working perfectly again. Thank you for the quick fix, @harlan-zw!
